# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
#
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme

# theme                  : "minimal-mistakes-jekyll"
# remote_theme           : "mmistakes/minimal-mistakes"


title: Simran Ketha
email: p20200021 [at] hyderabad.bits-pilani.ac.in
# subtitle: Deep Learning, Computational Neuroscience and Image Processing.
name: Simran Ketha
description: I am a PhD student researching selectivity, discriminability and ablation in deep neural network at BITS-Pilani Hyderabad.


twitter_username: Simran_Ketha
github_username: simranketha
linkedin_username: simranketha
minimal_mistakes_skin: dirt  #"default"  "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
# search: true

# Build settings
layout: single
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes


# Outputting
permalink: /:categories/:title/
paginate: 1 # amount of posts to show
paginate_path: blog/page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages


plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  avatar : "/assets/linkedin.JPG"
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/Simran_Ketha"
      
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/simranketha"
      
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/simranketha"
      
    - label: "ORCID"
      icon: "fab fa-fw fa-orcid"
      #url: "https://orcid.org/ID"
      
    - label: "simiketha19@gmail.com"
      icon: "fas fa-fw fa-envelope-square"
      url: mailto:simiketha19@gmail.com
      
    - label: "Research Gate"
      icon: "fab fa-fw fa-researchgate"
      url: "https://www.researchgate.net/profile/Simran-Ketha"
      
    - label: "Google Scholar"
      icon: "fab fa-fw fa-google-scholar"
      url: "https://scholar.google.com/citations?user=3k_akr4AAAAJ&hl=en"
defaults:
#   # _posts
#   - scope:
#       path: ""
#       type: posts
#     values:
#       layout: single
#       author_profile: true
#       read_time: true
#       comments: true
#       share: true
#       related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
